-- =============================================================================
-- Khel Drishti — live schema dump (READ-ONLY)
-- =============================================================================
-- Purpose : Reproduce the live Supabase "public" schema (plus the storage
--           buckets/policies and auth.users triggers the app relies on) as
--           plain DDL, so the repo can rebuild the database from scratch.
-- Safety  : Only reads system catalogs. Writes nothing, locks nothing beyond
--           normal catalog reads, and is safe to run against production.
-- Output  : One column `ddl`, one statement per row, already in dependency
--           order (extensions → types → sequences → functions → tables →
--           constraints → views → indexes → triggers → RLS → policies →
--           grants → storage). Save ALL rows, in order, to
--           supabase/live_schema_dump.sql — see scripts/db/README.md.
-- =============================================================================
WITH RECURSIVE
rels AS (
  SELECT c.oid, c.relname, c.relkind, n.nspname
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND NOT EXISTS (                      -- skip objects owned by extensions
      SELECT 1 FROM pg_depend d
      WHERE d.classid = 'pg_class'::regclass AND d.objid = c.oid AND d.deptype = 'e')
),
-- ---------------------------------------------------------------- header ----
hdr AS (
  SELECT 0 AS sec, 0 AS sub, ''::text AS k,
         '-- Generated ' || to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') || ' UTC'
         || E'\n-- Server: ' || version()
         || E'\n-- Applied migration versions on live: '
         || coalesce(CASE WHEN to_regclass('supabase_migrations.schema_migrations') IS NOT NULL THEN
              (xpath('/row/v/text()', query_to_xml(
                 'select string_agg(version::text, '','' order by version) as v from supabase_migrations.schema_migrations',
                 false, true, '')))[1]::text END, 'n/a')
         || E'\nSET check_function_bodies = false;\nSET client_min_messages = warning;' AS ddl
),
-- ------------------------------------------------------------ extensions ----
ext AS (
  -- Supabase platform extensions are emitted commented out: they do not exist
  -- on plain Postgres / RDS and the app does not use them.
  SELECT 10, 0, e.extname::text,
         CASE WHEN e.extname IN ('pg_graphql', 'pgsodium', 'supabase_vault', 'pg_net', 'pgjwt',
                                 'pg_stat_statements', 'pg_cron', 'pgaudit', 'pg_hashids', 'wrappers')
              THEN '-- platform extension, not recreated: '
              ELSE '' END
         || format('CREATE EXTENSION IF NOT EXISTS %I WITH SCHEMA %I;', e.extname, n.nspname)
  FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace
  WHERE e.extname <> 'plpgsql'
),
-- ----------------------------------------------------------------- enums ----
enums AS (
  SELECT 20, 0, t.typname::text,
         format('CREATE TYPE public.%I AS ENUM (%s);', t.typname,
                (SELECT string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder)
                 FROM pg_enum e WHERE e.enumtypid = t.oid))
  FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
  WHERE n.nspname = 'public' AND t.typtype = 'e'
),
-- ------------------------------------------------------------- sequences ----
seqs AS (
  SELECT 30, 0, r.relname::text,
         format('CREATE SEQUENCE IF NOT EXISTS public.%I AS %s START %s INCREMENT %s MINVALUE %s MAXVALUE %s%s;',
                r.relname, format_type(s.seqtypid, NULL), s.seqstart, s.seqincrement,
                s.seqmin, s.seqmax, CASE WHEN s.seqcycle THEN ' CYCLE' ELSE '' END)
  FROM rels r JOIN pg_sequence s ON s.seqrelid = r.oid
  WHERE r.relkind = 'S'
    AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid = r.oid AND d.deptype = 'i') -- identity seqs
),
-- ------------------------------------------------------------- functions ----
funcs AS (
  SELECT 40, 0, p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')',
         pg_get_functiondef(p.oid) || ';'
  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public' AND p.prokind IN ('f', 'p')
    AND NOT EXISTS (SELECT 1 FROM pg_depend d
                    WHERE d.classid = 'pg_proc'::regclass AND d.objid = p.oid AND d.deptype = 'e')
),
-- ---------------------------------------------------------------- tables ----
tabs AS (
  SELECT 50, 0, r.relname::text,
         format(E'CREATE TABLE public.%I (\n%s\n);', r.relname,
           coalesce((SELECT string_agg(
               format('  %I %s%s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
                 CASE a.attidentity WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
                                    WHEN 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY' ELSE '' END,
                 CASE WHEN a.attgenerated = 's'
                        THEN ' GENERATED ALWAYS AS (' || pg_get_expr(ad.adbin, ad.adrelid) || ') STORED'
                      WHEN ad.adbin IS NOT NULL
                        THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
                      ELSE '' END,
                 CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END),
               E',\n' ORDER BY a.attnum)
             FROM pg_attribute a
             LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
             WHERE a.attrelid = r.oid AND a.attnum > 0 AND NOT a.attisdropped), ''))
  FROM rels r WHERE r.relkind IN ('r', 'p')
),
-- ----------------------------------------------------------- constraints ----
cons AS (
  SELECT CASE WHEN co.contype = 'f' THEN 70 ELSE 60 END, 0, r.relname || '.' || co.conname,
         format('ALTER TABLE public.%I ADD CONSTRAINT %I %s;', r.relname, co.conname, pg_get_constraintdef(co.oid))
  FROM pg_constraint co JOIN rels r ON r.oid = co.conrelid
  WHERE co.contype IN ('p', 'u', 'c', 'x', 'f')
),
-- ----------------------------------------------- views (dependency order) ----
vdeps AS (
  SELECT DISTINCT rw.ev_class AS v, d.refobjid AS dep
  FROM pg_rewrite rw
  JOIN pg_depend d ON d.classid = 'pg_rewrite'::regclass AND d.objid = rw.oid
  JOIN rels dv ON dv.oid = d.refobjid AND dv.relkind IN ('v', 'm')
  WHERE d.refobjid <> rw.ev_class
),
vlvl(v, lvl) AS (
  SELECT oid, 0 FROM rels WHERE relkind IN ('v', 'm')
  UNION ALL
  SELECT vd.v, vl.lvl + 1 FROM vdeps vd JOIN vlvl vl ON vl.v = vd.dep
),
views AS (
  SELECT 90, max(vl.lvl), r.relname::text,
         CASE WHEN r.relkind = 'v' THEN
           format(E'CREATE VIEW public.%I%s AS\n%s', r.relname,
                  coalesce(' WITH (' || array_to_string(c.reloptions, ', ') || ')', ''),
                  rtrim(pg_get_viewdef(r.oid, true), E'; \n') || ';')
         ELSE
           format(E'CREATE MATERIALIZED VIEW public.%I AS\n%s\nWITH NO DATA;', r.relname,
                  rtrim(pg_get_viewdef(r.oid, true), E'; \n'))
         END
  FROM rels r JOIN pg_class c ON c.oid = r.oid JOIN vlvl vl ON vl.v = r.oid
  WHERE r.relkind IN ('v', 'm')
  GROUP BY r.oid, r.relname, r.relkind, c.reloptions
),
-- --------------------------------------------------------------- indexes ----
idx AS (
  SELECT 95, 0, ic.relname::text, pg_get_indexdef(i.indexrelid) || ';'
  FROM pg_index i
  JOIN rels r ON r.oid = i.indrelid
  JOIN pg_class ic ON ic.oid = i.indexrelid
  WHERE NOT EXISTS (SELECT 1 FROM pg_constraint co
                    WHERE co.conindid = i.indexrelid AND co.conrelid = i.indrelid
                      AND co.contype IN ('p', 'u', 'x'))
),
-- -------------------------------------------------------------- triggers ----
trg AS (
  SELECT 100, 0, n.nspname || '.' || c.relname || '.' || t.tgname, pg_get_triggerdef(t.oid, true) || ';'
  FROM pg_trigger t
  JOIN pg_class c ON c.oid = t.tgrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  JOIN pg_proc p ON p.oid = t.tgfoid
  JOIN pg_namespace pn ON pn.oid = p.pronamespace
  WHERE NOT t.tgisinternal
    AND (n.nspname = 'public' OR (n.nspname IN ('auth', 'storage') AND pn.nspname = 'public'))
),
-- ------------------------------------------------------------------- RLS ----
rls AS (
  SELECT 110, 0, r.relname::text,
         format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', r.relname)
         || CASE WHEN c.relforcerowsecurity THEN format(E'\nALTER TABLE public.%I FORCE ROW LEVEL SECURITY;', r.relname) ELSE '' END
  FROM rels r JOIN pg_class c ON c.oid = r.oid
  WHERE r.relkind IN ('r', 'p') AND c.relrowsecurity
),
pols AS (
  SELECT 120, 0, n.nspname || '.' || c.relname || '.' || pol.polname,
         format('CREATE POLICY %I ON %I.%I AS %s FOR %s TO %s%s%s;',
           pol.polname, n.nspname, c.relname,
           CASE WHEN pol.polpermissive THEN 'PERMISSIVE' ELSE 'RESTRICTIVE' END,
           CASE pol.polcmd WHEN 'r' THEN 'SELECT' WHEN 'a' THEN 'INSERT' WHEN 'w' THEN 'UPDATE'
                           WHEN 'd' THEN 'DELETE' ELSE 'ALL' END,
           CASE WHEN pol.polroles = '{0}'::oid[] THEN 'public'
                ELSE (SELECT string_agg(quote_ident(ro.rolname), ', ' ORDER BY ro.rolname)
                      FROM pg_roles ro WHERE ro.oid = ANY (pol.polroles)) END,
           CASE WHEN pol.polqual IS NOT NULL
                THEN E'\n  USING (' || pg_get_expr(pol.polqual, pol.polrelid) || ')' ELSE '' END,
           CASE WHEN pol.polwithcheck IS NOT NULL
                THEN E'\n  WITH CHECK (' || pg_get_expr(pol.polwithcheck, pol.polrelid) || ')' ELSE '' END)
  FROM pg_policy pol
  JOIN pg_class c ON c.oid = pol.polrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname IN ('public', 'storage')
),
-- ---------------------------------------------------------------- grants ----
-- Supabase grants ALL to anon/authenticated by default; emit the exact set so
-- any deliberate REVOKE on live is preserved.
rgrants AS (
  SELECT 130, 0, r.relname::text,
         format('REVOKE ALL ON public.%I FROM anon, authenticated, service_role;', r.relname)
         || coalesce((SELECT string_agg(format(E'\nGRANT %s ON public.%I TO %I;', g.privs, r.relname, g.rolname), '' ORDER BY g.rolname)
                      FROM (SELECT ro.rolname, string_agg(DISTINCT a.privilege_type, ', ') AS privs
                            FROM aclexplode(c.relacl) a JOIN pg_roles ro ON ro.oid = a.grantee
                            WHERE ro.rolname IN ('anon', 'authenticated', 'service_role')
                            GROUP BY ro.rolname) g), '')
  FROM rels r JOIN pg_class c ON c.oid = r.oid
  WHERE r.relkind IN ('r', 'p', 'v', 'm', 'S')
),
fgrants AS (
  SELECT 131, 0, p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')',
         format('REVOKE ALL ON FUNCTION public.%I(%s) FROM PUBLIC, anon, authenticated;',
                p.proname, pg_get_function_identity_arguments(p.oid))
         || coalesce((SELECT string_agg(format(E'\nGRANT EXECUTE ON FUNCTION public.%I(%s) TO %s;',
                                  p.proname, pg_get_function_identity_arguments(p.oid),
                                  CASE WHEN a.grantee = 0 THEN 'PUBLIC' ELSE quote_ident(ro.rolname) END), '')
                      FROM aclexplode(p.proacl) a LEFT JOIN pg_roles ro ON ro.oid = a.grantee
                      WHERE a.privilege_type = 'EXECUTE'
                        AND (a.grantee = 0 OR ro.rolname IN ('anon', 'authenticated', 'service_role'))), '')
  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public' AND p.prokind IN ('f', 'p') AND p.proacl IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM pg_depend d
                    WHERE d.classid = 'pg_proc'::regclass AND d.objid = p.oid AND d.deptype = 'e')
),
-- --------------------------------------------------------------- storage ----
buckets AS (
  SELECT 140, 0, b.id::text,
         format('INSERT INTO storage.buckets SELECT * FROM jsonb_populate_record(NULL::storage.buckets, %L::jsonb) ON CONFLICT (id) DO NOTHING;',
                (to_jsonb(b) - 'created_at' - 'updated_at' - 'owner' - 'owner_id')::text)
  FROM storage.buckets b
),
-- ---------------------------------------------------------- row counts -----
counts AS (
  SELECT 999, 0, r.relname::text,
         format('-- rows %s: %s', r.relname,
                (xpath('/row/c/text()', query_to_xml(format('select count(*) as c from public.%I', r.relname),
                                                     false, true, '')))[1]::text)
  FROM rels r WHERE r.relkind IN ('r', 'p')
)
SELECT ddl FROM (
  SELECT * FROM hdr
  UNION ALL SELECT * FROM ext
  UNION ALL SELECT * FROM enums
  UNION ALL SELECT * FROM seqs
  UNION ALL SELECT * FROM funcs
  UNION ALL SELECT * FROM tabs
  UNION ALL SELECT * FROM cons
  UNION ALL SELECT * FROM views
  UNION ALL SELECT * FROM idx
  UNION ALL SELECT * FROM trg
  UNION ALL SELECT * FROM rls
  UNION ALL SELECT * FROM pols
  UNION ALL SELECT * FROM rgrants
  UNION ALL SELECT * FROM fgrants
  UNION ALL SELECT * FROM buckets
  UNION ALL SELECT * FROM counts
) all_ddl
ORDER BY sec, sub, k;
